---
- name: Connect to EC2 instance
  hosts: all-host
  tasks:
    - name: Check connectivity
      command: echo "Successfully connected to EC2 instance!"

- name: Update host
  hosts: all-host
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
